server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-service
    gateway:
      routes:
        - id: checkout-service-id
          uri: lb://checkout-service
          predicates:
          - Path=/checkout
          filters:
          - AddRequestHeader=X-Request-from, gateway
          - AddResponseHeader=X-Response-Red, Blue
        - id: products-service-id
          uri: lb://products-service
          predicates:
          - Path=/products
